[project]
name = "comfybros"
version = "0.1.0"
description = "Custom ComfyUI nodes for enhanced text and image processing"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "pillow>=9.0.0",
    "numpy>=1.21.0",
    "requests>=2.25.0"
]
